version: '2'
services:
  sqlserver:
    image: microsoft/mssql-server-linux:latest
    hostname: 'svrsqlexpress'
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: P@ssw0rd#1
      MSSQL_PID: Express
    ports:
      - '1434:1433'
    volumes:
      - /srv/docker-data/sqlexpressdata:/var/opt/mssql
